version: "2.2"
services:
  bomen1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: bomen1
    environment:
      - node.name=bomen1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=bomen2,bomen3
      - cluster.initial_master_nodes=bomen1,bomen2,bomen3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  bomen2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: bomen2
    environment:
      - node.name=bomen2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=bomen1,bomen3
      - cluster.initial_master_nodes=bomen1,bomen2,bomen3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic

  bomen3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: bomen3
    environment:
      - node.name=es3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=bomen1,bomen2
      - cluster.initial_master_nodes=bomen1,bomen2,bomen3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - elastic

  kibana1:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://bomen1:9200
      ELASTICSEARCH_HOSTS: http://bomen1:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
